services:
  - mysql
addons:
  apt:
    packages:
      - ant
before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('dev') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
install:
  #- rm $TRAVIS_BUILD_DIR/tools/phpunit
  #- composer require --dev phpunit/phpunit ~6.5.5
  #- $TRAVIS_BUILD_DIR/vendor/bin/phpunit --version
  #- cp $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/tools
script: ant build-ci
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
after_failure: "cat /tmp/icehrm.test.log"
