# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: icehrm_php
#build: ./opt/docker/icehrm/docker

pipelines:
  default:
    - step:
        script:
          - gulp
          - cd /opt/docker/icehrm/core/robo && php robo.phar migrate:all app
