version: "3.5"
services:
    php:
        working_dir: /var/www/dev-php
#        image: ducnhat/icehrm:latest
        build: ./docker
        volumes:
            - .:/var/www/dev-php
        environment:
            APP_DEBUG: "true"
        ports:
            - 8080:80
        links:
            - mysql
            - memcached
        depends_on:
            - mysql
            - memcached

    mysql:
        image: percona:5.5
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yviet
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        ports:
            - 3307:3306
        volumes:
            - mysql-vol:/var/lib/mysql

    memcached:
        image: memcached:1.6.17-alpine
        restart: always

volumes:
    mysql-vol:
        driver: local
