version: "3.5"
services:
    php:
        working_dir: /var/www/dev-php
#        image: ducnhat/icehrm:latest
        build: ./docker
        volumes:
            - .:/var/www/dev-php
        environment:
            APP_DEBUG: "true"
        ports:
            - 8080:80
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: percona:5.5
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yviet
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        ports:
            - 3307:3306
        volumes:
            - mysql-vol:/var/lib/mysql

volumes:
  mysql-vol:
    driver: local
