<?php

namespace Classes\Migration;

/**
 * Class v20200322_161501_add_employee_full_working_days
 */
class v20200322_161501_add_employee_full_working_day extends AbstractMigration
{
    public function up()
    {
        $sql = "INSERT INTO CustomFields (`type`, name, `data`, display, created, updated, field_type, field_label, field_validation, field_options, display_order, display_section) VALUES('Employee', 'full_working_days', '[\"full_working_days\",{\"label\":\"Ngày bắt đầu tính đủ công\",\"type\":\"date\",\"validation\":\"none\"}]', 'Form', NULL, '2020-03-22 14:37:28.0', 'date', 'Ngày bắt đầu tính đủ công', 'none', '', 16, '');
";

        $this->executeQuery($sql);
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }
}
