<?php

namespace Classes\Migration;

class v20200518_225710_update_employee_report extends AbstractMigration
{
    public function up()
    {
        $sql = "
UPDATE Reports
SET name='Báo Cáo Danh Sách Nhân Viên', details='Xuất Báo Cáo Danh Sách Nhân Viên', parameters='[[\"employment_status\", {\"label\":\"Employment Status\",\"type\":\"select2\",\"remote-source\":[\"EmploymentStatus\",\"id\",\"name\"],\"allow-null\":true}],[\"job_title\", {\"label\":\"Job Title\",\"type\":\"select2\",\"remote-source\":[\"JobTitle\",\"id\",\"name\"],\"allow-null\":true}]]', query='EmployeeDetailsReport', paramOrder='[\"employment_status\",\"job_title\"]', `type`='Class', report_group='Employee Information', `output`='XLSX'
WHERE query='EmployeeDetailsReport';
";
        $this->executeQuery($sql);
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }
}