<?php

namespace Classes\Migration;

class v20200518_225711_update_employee_report extends AbstractMigration
{
    public function up()
    {
        $sql = "
DELETE FROM CustomFields WHERE `name`='deparment';
DELETE FROM CustomFields WHERE `name`='indirect-supervisor';
";
        $this->executeQuery($sql);
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }
}