<?php


namespace Classes\Migration;


/**
 * Class v20200415_234355_create_employee_salary_deposit
 * @package Classes\Migration
 */
class v20200415_234355_create_employeeSalaryDeposit extends AbstractMigration
{
    public function up()
    {
        $sql = "
CREATE TABLE `EmployeeSalaryDeposit` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `employee` bigint(20) NOT NULL,
  `amount` bigint(20) NOT NULL,
  `date` datetime NOT NULL,
  `details` text,
  PRIMARY KEY (`id`),
  KEY `Fk_EmployeeSalary_Employee` (`employee`),
  CONSTRAINT `Fk_EmployeeSalaryDeposit_Employee` FOREIGN KEY (`employee`) REFERENCES `Employees` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=83 DEFAULT CHARSET=utf8;";
        $this->executeQuery($sql);
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }
}
