<?php
/**
 * Created by PhpStorm.
 * User: Thilina
 * Date: 8/13/17
 * Time: 8:04 AM
 */

namespace Attendance\Common\Model;

use Model\BaseModel;

class Attendance extends BaseModel
{
    public $table = 'Attendance';

    public function getAdminAccess()
    {
        return array('get', 'element', 'save', 'delete');
    }

    public function getManagerAccess()
    {
        return array('get', 'element', 'save', 'delete');
    }

    public function getUserAccess()
    {
        return array('get');
    }

    public function getUserOnlyMeAccess()
    {
        return array('element', 'save', 'delete');
    }

    public function Find($whereOrderBy, $bindarr = false, $pkeysArr = false, $extra = array())
    {
        if (is_array($bindarr)) {
            foreach ($bindarr as $index => $value) {
                if ($index < 1) {
                    continue;
                }

                if (stripos($value, '/') === false) {
                    continue;
                }

                $value = str_replace('%', '', $value);
                $value = explode('/', $value);
                if ((int)$value[0] < 10) {
                    $value[0] = "0{$value[0]}";
                }
                $value = array_reverse($value);
                $value = implode('-', $value);
                $bindarr[$index] = "%{$value}%";
            }
        }

        return parent::Find($whereOrderBy, $bindarr, $pkeysArr, $extra); // TODO: Change the autogenerated stub
    }
}
